// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/Function.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	awscdk "github.com/aws/aws-cdk-go/awscdk/v2"
	awscloudwatch "github.com/aws/aws-cdk-go/awscdk/v2/awscloudwatch"
	awsec2 "github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	awsiam "github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	awslambda "github.com/aws/aws-cdk-go/awscdk/v2/awslambda"
	awslogs "github.com/aws/aws-cdk-go/awscdk/v2/awslogs"
	awssns "github.com/aws/aws-cdk-go/awscdk/v2/awssns"
	awssqs "github.com/aws/aws-cdk-go/awscdk/v2/awssqs"
	constructs "github.com/aws/constructs-go/constructs/v10"
	gomock "github.com/golang/mock/gomock"
)

// MockFunction is a mock of Function interface.
type MockFunction struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionMockRecorder
}

// MockFunctionMockRecorder is the mock recorder for MockFunction.
type MockFunctionMockRecorder struct {
	mock *MockFunction
}

// NewMockFunction creates a new mock instance.
func NewMockFunction(ctrl *gomock.Controller) *MockFunction {
	mock := &MockFunction{ctrl: ctrl}
	mock.recorder = &MockFunctionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFunction) EXPECT() *MockFunctionMockRecorder {
	return m.recorder
}

// AddAlias mocks base method.
func (m *MockFunction) AddAlias(aliasName *string, options *awslambda.AliasOptions) awslambda.Alias {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAlias", aliasName, options)
	ret0, _ := ret[0].(awslambda.Alias)
	return ret0
}

// AddAlias indicates an expected call of AddAlias.
func (mr *MockFunctionMockRecorder) AddAlias(aliasName, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlias", reflect.TypeOf((*MockFunction)(nil).AddAlias), aliasName, options)
}

// AddEnvironment mocks base method.
func (m *MockFunction) AddEnvironment(key, value *string, options *awslambda.EnvironmentOptions) awslambda.Function {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEnvironment", key, value, options)
	ret0, _ := ret[0].(awslambda.Function)
	return ret0
}

// AddEnvironment indicates an expected call of AddEnvironment.
func (mr *MockFunctionMockRecorder) AddEnvironment(key, value, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEnvironment", reflect.TypeOf((*MockFunction)(nil).AddEnvironment), key, value, options)
}

// AddEventSource mocks base method.
func (m *MockFunction) AddEventSource(source awslambda.IEventSource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddEventSource", source)
}

// AddEventSource indicates an expected call of AddEventSource.
func (mr *MockFunctionMockRecorder) AddEventSource(source interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventSource", reflect.TypeOf((*MockFunction)(nil).AddEventSource), source)
}

// AddEventSourceMapping mocks base method.
func (m *MockFunction) AddEventSourceMapping(id *string, options *awslambda.EventSourceMappingOptions) awslambda.EventSourceMapping {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventSourceMapping", id, options)
	ret0, _ := ret[0].(awslambda.EventSourceMapping)
	return ret0
}

// AddEventSourceMapping indicates an expected call of AddEventSourceMapping.
func (mr *MockFunctionMockRecorder) AddEventSourceMapping(id, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventSourceMapping", reflect.TypeOf((*MockFunction)(nil).AddEventSourceMapping), id, options)
}

// AddFunctionUrl mocks base method.
func (m *MockFunction) AddFunctionUrl(options *awslambda.FunctionUrlOptions) awslambda.FunctionUrl {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFunctionUrl", options)
	ret0, _ := ret[0].(awslambda.FunctionUrl)
	return ret0
}

// AddFunctionUrl indicates an expected call of AddFunctionUrl.
func (mr *MockFunctionMockRecorder) AddFunctionUrl(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFunctionUrl", reflect.TypeOf((*MockFunction)(nil).AddFunctionUrl), options)
}

// AddLayers mocks base method.
func (m *MockFunction) AddLayers(layers ...awslambda.ILayerVersion) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range layers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddLayers", varargs...)
}

// AddLayers indicates an expected call of AddLayers.
func (mr *MockFunctionMockRecorder) AddLayers(layers ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLayers", reflect.TypeOf((*MockFunction)(nil).AddLayers), layers...)
}

// AddPermission mocks base method.
func (m *MockFunction) AddPermission(id *string, permission *awslambda.Permission) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPermission", id, permission)
}

// AddPermission indicates an expected call of AddPermission.
func (mr *MockFunctionMockRecorder) AddPermission(id, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermission", reflect.TypeOf((*MockFunction)(nil).AddPermission), id, permission)
}

// AddToRolePolicy mocks base method.
func (m *MockFunction) AddToRolePolicy(statement awsiam.PolicyStatement) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddToRolePolicy", statement)
}

// AddToRolePolicy indicates an expected call of AddToRolePolicy.
func (mr *MockFunctionMockRecorder) AddToRolePolicy(statement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToRolePolicy", reflect.TypeOf((*MockFunction)(nil).AddToRolePolicy), statement)
}

// ApplyRemovalPolicy mocks base method.
func (m *MockFunction) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyRemovalPolicy", policy)
}

// ApplyRemovalPolicy indicates an expected call of ApplyRemovalPolicy.
func (mr *MockFunctionMockRecorder) ApplyRemovalPolicy(policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRemovalPolicy", reflect.TypeOf((*MockFunction)(nil).ApplyRemovalPolicy), policy)
}

// Architecture mocks base method.
func (m *MockFunction) Architecture() awslambda.Architecture {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Architecture")
	ret0, _ := ret[0].(awslambda.Architecture)
	return ret0
}

// Architecture indicates an expected call of Architecture.
func (mr *MockFunctionMockRecorder) Architecture() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Architecture", reflect.TypeOf((*MockFunction)(nil).Architecture))
}

// CanCreatePermissions mocks base method.
func (m *MockFunction) CanCreatePermissions() *bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanCreatePermissions")
	ret0, _ := ret[0].(*bool)
	return ret0
}

// CanCreatePermissions indicates an expected call of CanCreatePermissions.
func (mr *MockFunctionMockRecorder) CanCreatePermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanCreatePermissions", reflect.TypeOf((*MockFunction)(nil).CanCreatePermissions))
}

// ConfigureAsyncInvoke mocks base method.
func (m *MockFunction) ConfigureAsyncInvoke(options *awslambda.EventInvokeConfigOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureAsyncInvoke", options)
}

// ConfigureAsyncInvoke indicates an expected call of ConfigureAsyncInvoke.
func (mr *MockFunctionMockRecorder) ConfigureAsyncInvoke(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureAsyncInvoke", reflect.TypeOf((*MockFunction)(nil).ConfigureAsyncInvoke), options)
}

// Connections mocks base method.
func (m *MockFunction) Connections() awsec2.Connections {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connections")
	ret0, _ := ret[0].(awsec2.Connections)
	return ret0
}

// Connections indicates an expected call of Connections.
func (mr *MockFunctionMockRecorder) Connections() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connections", reflect.TypeOf((*MockFunction)(nil).Connections))
}

// ConsiderWarningOnInvokeFunctionPermissions mocks base method.
func (m *MockFunction) ConsiderWarningOnInvokeFunctionPermissions(scope constructs.Construct, action *string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConsiderWarningOnInvokeFunctionPermissions", scope, action)
}

// ConsiderWarningOnInvokeFunctionPermissions indicates an expected call of ConsiderWarningOnInvokeFunctionPermissions.
func (mr *MockFunctionMockRecorder) ConsiderWarningOnInvokeFunctionPermissions(scope, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsiderWarningOnInvokeFunctionPermissions", reflect.TypeOf((*MockFunction)(nil).ConsiderWarningOnInvokeFunctionPermissions), scope, action)
}

// CurrentVersion mocks base method.
func (m *MockFunction) CurrentVersion() awslambda.Version {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentVersion")
	ret0, _ := ret[0].(awslambda.Version)
	return ret0
}

// CurrentVersion indicates an expected call of CurrentVersion.
func (mr *MockFunctionMockRecorder) CurrentVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentVersion", reflect.TypeOf((*MockFunction)(nil).CurrentVersion))
}

// DeadLetterQueue mocks base method.
func (m *MockFunction) DeadLetterQueue() awssqs.IQueue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeadLetterQueue")
	ret0, _ := ret[0].(awssqs.IQueue)
	return ret0
}

// DeadLetterQueue indicates an expected call of DeadLetterQueue.
func (mr *MockFunctionMockRecorder) DeadLetterQueue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadLetterQueue", reflect.TypeOf((*MockFunction)(nil).DeadLetterQueue))
}

// DeadLetterTopic mocks base method.
func (m *MockFunction) DeadLetterTopic() awssns.ITopic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeadLetterTopic")
	ret0, _ := ret[0].(awssns.ITopic)
	return ret0
}

// DeadLetterTopic indicates an expected call of DeadLetterTopic.
func (mr *MockFunctionMockRecorder) DeadLetterTopic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadLetterTopic", reflect.TypeOf((*MockFunction)(nil).DeadLetterTopic))
}

// Env mocks base method.
func (m *MockFunction) Env() *awscdk.ResourceEnvironment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(*awscdk.ResourceEnvironment)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockFunctionMockRecorder) Env() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockFunction)(nil).Env))
}

// FunctionArn mocks base method.
func (m *MockFunction) FunctionArn() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FunctionArn")
	ret0, _ := ret[0].(*string)
	return ret0
}

// FunctionArn indicates an expected call of FunctionArn.
func (mr *MockFunctionMockRecorder) FunctionArn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FunctionArn", reflect.TypeOf((*MockFunction)(nil).FunctionArn))
}

// FunctionName mocks base method.
func (m *MockFunction) FunctionName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FunctionName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// FunctionName indicates an expected call of FunctionName.
func (mr *MockFunctionMockRecorder) FunctionName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FunctionName", reflect.TypeOf((*MockFunction)(nil).FunctionName))
}

// GeneratePhysicalName mocks base method.
func (m *MockFunction) GeneratePhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// GeneratePhysicalName indicates an expected call of GeneratePhysicalName.
func (mr *MockFunctionMockRecorder) GeneratePhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePhysicalName", reflect.TypeOf((*MockFunction)(nil).GeneratePhysicalName))
}

// GetResourceArnAttribute mocks base method.
func (m *MockFunction) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceArnAttribute", arnAttr, arnComponents)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceArnAttribute indicates an expected call of GetResourceArnAttribute.
func (mr *MockFunctionMockRecorder) GetResourceArnAttribute(arnAttr, arnComponents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceArnAttribute", reflect.TypeOf((*MockFunction)(nil).GetResourceArnAttribute), arnAttr, arnComponents)
}

// GetResourceNameAttribute mocks base method.
func (m *MockFunction) GetResourceNameAttribute(nameAttr *string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceNameAttribute", nameAttr)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceNameAttribute indicates an expected call of GetResourceNameAttribute.
func (mr *MockFunctionMockRecorder) GetResourceNameAttribute(nameAttr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceNameAttribute", reflect.TypeOf((*MockFunction)(nil).GetResourceNameAttribute), nameAttr)
}

// GrantInvoke mocks base method.
func (m *MockFunction) GrantInvoke(identity awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantInvoke", identity)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantInvoke indicates an expected call of GrantInvoke.
func (mr *MockFunctionMockRecorder) GrantInvoke(identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantInvoke", reflect.TypeOf((*MockFunction)(nil).GrantInvoke), identity)
}

// GrantInvokeCompositePrincipal mocks base method.
func (m *MockFunction) GrantInvokeCompositePrincipal(compositePrincipal awsiam.CompositePrincipal) *[]awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantInvokeCompositePrincipal", compositePrincipal)
	ret0, _ := ret[0].(*[]awsiam.Grant)
	return ret0
}

// GrantInvokeCompositePrincipal indicates an expected call of GrantInvokeCompositePrincipal.
func (mr *MockFunctionMockRecorder) GrantInvokeCompositePrincipal(compositePrincipal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantInvokeCompositePrincipal", reflect.TypeOf((*MockFunction)(nil).GrantInvokeCompositePrincipal), compositePrincipal)
}

// GrantInvokeLatestVersion mocks base method.
func (m *MockFunction) GrantInvokeLatestVersion(identity awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantInvokeLatestVersion", identity)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantInvokeLatestVersion indicates an expected call of GrantInvokeLatestVersion.
func (mr *MockFunctionMockRecorder) GrantInvokeLatestVersion(identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantInvokeLatestVersion", reflect.TypeOf((*MockFunction)(nil).GrantInvokeLatestVersion), identity)
}

// GrantInvokeUrl mocks base method.
func (m *MockFunction) GrantInvokeUrl(identity awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantInvokeUrl", identity)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantInvokeUrl indicates an expected call of GrantInvokeUrl.
func (mr *MockFunctionMockRecorder) GrantInvokeUrl(identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantInvokeUrl", reflect.TypeOf((*MockFunction)(nil).GrantInvokeUrl), identity)
}

// GrantInvokeVersion mocks base method.
func (m *MockFunction) GrantInvokeVersion(identity awsiam.IGrantable, version awslambda.IVersion) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantInvokeVersion", identity, version)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantInvokeVersion indicates an expected call of GrantInvokeVersion.
func (mr *MockFunctionMockRecorder) GrantInvokeVersion(identity, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantInvokeVersion", reflect.TypeOf((*MockFunction)(nil).GrantInvokeVersion), identity, version)
}

// GrantPrincipal mocks base method.
func (m *MockFunction) GrantPrincipal() awsiam.IPrincipal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantPrincipal")
	ret0, _ := ret[0].(awsiam.IPrincipal)
	return ret0
}

// GrantPrincipal indicates an expected call of GrantPrincipal.
func (mr *MockFunctionMockRecorder) GrantPrincipal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantPrincipal", reflect.TypeOf((*MockFunction)(nil).GrantPrincipal))
}

// InvalidateVersionBasedOn mocks base method.
func (m *MockFunction) InvalidateVersionBasedOn(x *string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateVersionBasedOn", x)
}

// InvalidateVersionBasedOn indicates an expected call of InvalidateVersionBasedOn.
func (mr *MockFunctionMockRecorder) InvalidateVersionBasedOn(x interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateVersionBasedOn", reflect.TypeOf((*MockFunction)(nil).InvalidateVersionBasedOn), x)
}

// IsBoundToVpc mocks base method.
func (m *MockFunction) IsBoundToVpc() *bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBoundToVpc")
	ret0, _ := ret[0].(*bool)
	return ret0
}

// IsBoundToVpc indicates an expected call of IsBoundToVpc.
func (mr *MockFunctionMockRecorder) IsBoundToVpc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBoundToVpc", reflect.TypeOf((*MockFunction)(nil).IsBoundToVpc))
}

// LatestVersion mocks base method.
func (m *MockFunction) LatestVersion() awslambda.IVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersion")
	ret0, _ := ret[0].(awslambda.IVersion)
	return ret0
}

// LatestVersion indicates an expected call of LatestVersion.
func (mr *MockFunctionMockRecorder) LatestVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersion", reflect.TypeOf((*MockFunction)(nil).LatestVersion))
}

// LogGroup mocks base method.
func (m *MockFunction) LogGroup() awslogs.ILogGroup {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogGroup")
	ret0, _ := ret[0].(awslogs.ILogGroup)
	return ret0
}

// LogGroup indicates an expected call of LogGroup.
func (mr *MockFunctionMockRecorder) LogGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogGroup", reflect.TypeOf((*MockFunction)(nil).LogGroup))
}

// Metric mocks base method.
func (m *MockFunction) Metric(metricName *string, props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metric", metricName, props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// Metric indicates an expected call of Metric.
func (mr *MockFunctionMockRecorder) Metric(metricName, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metric", reflect.TypeOf((*MockFunction)(nil).Metric), metricName, props)
}

// MetricDuration mocks base method.
func (m *MockFunction) MetricDuration(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricDuration", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricDuration indicates an expected call of MetricDuration.
func (mr *MockFunctionMockRecorder) MetricDuration(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricDuration", reflect.TypeOf((*MockFunction)(nil).MetricDuration), props)
}

// MetricErrors mocks base method.
func (m *MockFunction) MetricErrors(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricErrors", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricErrors indicates an expected call of MetricErrors.
func (mr *MockFunctionMockRecorder) MetricErrors(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricErrors", reflect.TypeOf((*MockFunction)(nil).MetricErrors), props)
}

// MetricInvocations mocks base method.
func (m *MockFunction) MetricInvocations(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricInvocations", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricInvocations indicates an expected call of MetricInvocations.
func (mr *MockFunctionMockRecorder) MetricInvocations(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricInvocations", reflect.TypeOf((*MockFunction)(nil).MetricInvocations), props)
}

// MetricThrottles mocks base method.
func (m *MockFunction) MetricThrottles(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricThrottles", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricThrottles indicates an expected call of MetricThrottles.
func (mr *MockFunctionMockRecorder) MetricThrottles(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricThrottles", reflect.TypeOf((*MockFunction)(nil).MetricThrottles), props)
}

// Node mocks base method.
func (m *MockFunction) Node() constructs.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node")
	ret0, _ := ret[0].(constructs.Node)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockFunctionMockRecorder) Node() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockFunction)(nil).Node))
}

// PermissionsNode mocks base method.
func (m *MockFunction) PermissionsNode() constructs.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionsNode")
	ret0, _ := ret[0].(constructs.Node)
	return ret0
}

// PermissionsNode indicates an expected call of PermissionsNode.
func (mr *MockFunctionMockRecorder) PermissionsNode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionsNode", reflect.TypeOf((*MockFunction)(nil).PermissionsNode))
}

// PhysicalName mocks base method.
func (m *MockFunction) PhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// PhysicalName indicates an expected call of PhysicalName.
func (mr *MockFunctionMockRecorder) PhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalName", reflect.TypeOf((*MockFunction)(nil).PhysicalName))
}

// ResourceArnsForGrantInvoke mocks base method.
func (m *MockFunction) ResourceArnsForGrantInvoke() *[]*string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceArnsForGrantInvoke")
	ret0, _ := ret[0].(*[]*string)
	return ret0
}

// ResourceArnsForGrantInvoke indicates an expected call of ResourceArnsForGrantInvoke.
func (mr *MockFunctionMockRecorder) ResourceArnsForGrantInvoke() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceArnsForGrantInvoke", reflect.TypeOf((*MockFunction)(nil).ResourceArnsForGrantInvoke))
}

// Role mocks base method.
func (m *MockFunction) Role() awsiam.IRole {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Role")
	ret0, _ := ret[0].(awsiam.IRole)
	return ret0
}

// Role indicates an expected call of Role.
func (mr *MockFunctionMockRecorder) Role() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Role", reflect.TypeOf((*MockFunction)(nil).Role))
}

// Runtime mocks base method.
func (m *MockFunction) Runtime() awslambda.Runtime {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Runtime")
	ret0, _ := ret[0].(awslambda.Runtime)
	return ret0
}

// Runtime indicates an expected call of Runtime.
func (mr *MockFunctionMockRecorder) Runtime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Runtime", reflect.TypeOf((*MockFunction)(nil).Runtime))
}

// Stack mocks base method.
func (m *MockFunction) Stack() awscdk.Stack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stack")
	ret0, _ := ret[0].(awscdk.Stack)
	return ret0
}

// Stack indicates an expected call of Stack.
func (mr *MockFunctionMockRecorder) Stack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stack", reflect.TypeOf((*MockFunction)(nil).Stack))
}

// Timeout mocks base method.
func (m *MockFunction) Timeout() awscdk.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeout")
	ret0, _ := ret[0].(awscdk.Duration)
	return ret0
}

// Timeout indicates an expected call of Timeout.
func (mr *MockFunctionMockRecorder) Timeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeout", reflect.TypeOf((*MockFunction)(nil).Timeout))
}

// ToString mocks base method.
func (m *MockFunction) ToString() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockFunctionMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockFunction)(nil).ToString))
}

// WarnInvokeFunctionPermissions mocks base method.
func (m *MockFunction) WarnInvokeFunctionPermissions(scope constructs.Construct) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WarnInvokeFunctionPermissions", scope)
}

// WarnInvokeFunctionPermissions indicates an expected call of WarnInvokeFunctionPermissions.
func (mr *MockFunctionMockRecorder) WarnInvokeFunctionPermissions(scope interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnInvokeFunctionPermissions", reflect.TypeOf((*MockFunction)(nil).WarnInvokeFunctionPermissions), scope)
}
