// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/Table.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	awscdk "github.com/aws/aws-cdk-go/awscdk/v2"
	awscloudwatch "github.com/aws/aws-cdk-go/awscdk/v2/awscloudwatch"
	awsdynamodb "github.com/aws/aws-cdk-go/awscdk/v2/awsdynamodb"
	awsiam "github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	awskms "github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	constructs "github.com/aws/constructs-go/constructs/v10"
	gomock "github.com/golang/mock/gomock"
)

// MockTable is a mock of Table interface.
type MockTable struct {
	ctrl     *gomock.Controller
	recorder *MockTableMockRecorder
}

// MockTableMockRecorder is the mock recorder for MockTable.
type MockTableMockRecorder struct {
	mock *MockTable
}

// NewMockTable creates a new mock instance.
func NewMockTable(ctrl *gomock.Controller) *MockTable {
	mock := &MockTable{ctrl: ctrl}
	mock.recorder = &MockTableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTable) EXPECT() *MockTableMockRecorder {
	return m.recorder
}

// AddGlobalSecondaryIndex mocks base method.
func (m *MockTable) AddGlobalSecondaryIndex(props *awsdynamodb.GlobalSecondaryIndexProps) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddGlobalSecondaryIndex", props)
}

// AddGlobalSecondaryIndex indicates an expected call of AddGlobalSecondaryIndex.
func (mr *MockTableMockRecorder) AddGlobalSecondaryIndex(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGlobalSecondaryIndex", reflect.TypeOf((*MockTable)(nil).AddGlobalSecondaryIndex), props)
}

// AddLocalSecondaryIndex mocks base method.
func (m *MockTable) AddLocalSecondaryIndex(props *awsdynamodb.LocalSecondaryIndexProps) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLocalSecondaryIndex", props)
}

// AddLocalSecondaryIndex indicates an expected call of AddLocalSecondaryIndex.
func (mr *MockTableMockRecorder) AddLocalSecondaryIndex(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLocalSecondaryIndex", reflect.TypeOf((*MockTable)(nil).AddLocalSecondaryIndex), props)
}

// AddToResourcePolicy mocks base method.
func (m *MockTable) AddToResourcePolicy(statement awsiam.PolicyStatement) *awsiam.AddToResourcePolicyResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToResourcePolicy", statement)
	ret0, _ := ret[0].(*awsiam.AddToResourcePolicyResult)
	return ret0
}

// AddToResourcePolicy indicates an expected call of AddToResourcePolicy.
func (mr *MockTableMockRecorder) AddToResourcePolicy(statement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToResourcePolicy", reflect.TypeOf((*MockTable)(nil).AddToResourcePolicy), statement)
}

// ApplyRemovalPolicy mocks base method.
func (m *MockTable) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyRemovalPolicy", policy)
}

// ApplyRemovalPolicy indicates an expected call of ApplyRemovalPolicy.
func (mr *MockTableMockRecorder) ApplyRemovalPolicy(policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRemovalPolicy", reflect.TypeOf((*MockTable)(nil).ApplyRemovalPolicy), policy)
}

// AutoScaleGlobalSecondaryIndexReadCapacity mocks base method.
func (m *MockTable) AutoScaleGlobalSecondaryIndexReadCapacity(indexName *string, props *awsdynamodb.EnableScalingProps) awsdynamodb.IScalableTableAttribute {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoScaleGlobalSecondaryIndexReadCapacity", indexName, props)
	ret0, _ := ret[0].(awsdynamodb.IScalableTableAttribute)
	return ret0
}

// AutoScaleGlobalSecondaryIndexReadCapacity indicates an expected call of AutoScaleGlobalSecondaryIndexReadCapacity.
func (mr *MockTableMockRecorder) AutoScaleGlobalSecondaryIndexReadCapacity(indexName, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoScaleGlobalSecondaryIndexReadCapacity", reflect.TypeOf((*MockTable)(nil).AutoScaleGlobalSecondaryIndexReadCapacity), indexName, props)
}

// AutoScaleGlobalSecondaryIndexWriteCapacity mocks base method.
func (m *MockTable) AutoScaleGlobalSecondaryIndexWriteCapacity(indexName *string, props *awsdynamodb.EnableScalingProps) awsdynamodb.IScalableTableAttribute {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoScaleGlobalSecondaryIndexWriteCapacity", indexName, props)
	ret0, _ := ret[0].(awsdynamodb.IScalableTableAttribute)
	return ret0
}

// AutoScaleGlobalSecondaryIndexWriteCapacity indicates an expected call of AutoScaleGlobalSecondaryIndexWriteCapacity.
func (mr *MockTableMockRecorder) AutoScaleGlobalSecondaryIndexWriteCapacity(indexName, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoScaleGlobalSecondaryIndexWriteCapacity", reflect.TypeOf((*MockTable)(nil).AutoScaleGlobalSecondaryIndexWriteCapacity), indexName, props)
}

// AutoScaleReadCapacity mocks base method.
func (m *MockTable) AutoScaleReadCapacity(props *awsdynamodb.EnableScalingProps) awsdynamodb.IScalableTableAttribute {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoScaleReadCapacity", props)
	ret0, _ := ret[0].(awsdynamodb.IScalableTableAttribute)
	return ret0
}

// AutoScaleReadCapacity indicates an expected call of AutoScaleReadCapacity.
func (mr *MockTableMockRecorder) AutoScaleReadCapacity(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoScaleReadCapacity", reflect.TypeOf((*MockTable)(nil).AutoScaleReadCapacity), props)
}

// AutoScaleWriteCapacity mocks base method.
func (m *MockTable) AutoScaleWriteCapacity(props *awsdynamodb.EnableScalingProps) awsdynamodb.IScalableTableAttribute {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoScaleWriteCapacity", props)
	ret0, _ := ret[0].(awsdynamodb.IScalableTableAttribute)
	return ret0
}

// AutoScaleWriteCapacity indicates an expected call of AutoScaleWriteCapacity.
func (mr *MockTableMockRecorder) AutoScaleWriteCapacity(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoScaleWriteCapacity", reflect.TypeOf((*MockTable)(nil).AutoScaleWriteCapacity), props)
}

// EncryptionKey mocks base method.
func (m *MockTable) EncryptionKey() awskms.IKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptionKey")
	ret0, _ := ret[0].(awskms.IKey)
	return ret0
}

// EncryptionKey indicates an expected call of EncryptionKey.
func (mr *MockTableMockRecorder) EncryptionKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptionKey", reflect.TypeOf((*MockTable)(nil).EncryptionKey))
}

// Env mocks base method.
func (m *MockTable) Env() *awscdk.ResourceEnvironment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(*awscdk.ResourceEnvironment)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockTableMockRecorder) Env() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockTable)(nil).Env))
}

// GeneratePhysicalName mocks base method.
func (m *MockTable) GeneratePhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// GeneratePhysicalName indicates an expected call of GeneratePhysicalName.
func (mr *MockTableMockRecorder) GeneratePhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePhysicalName", reflect.TypeOf((*MockTable)(nil).GeneratePhysicalName))
}

// GetResourceArnAttribute mocks base method.
func (m *MockTable) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceArnAttribute", arnAttr, arnComponents)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceArnAttribute indicates an expected call of GetResourceArnAttribute.
func (mr *MockTableMockRecorder) GetResourceArnAttribute(arnAttr, arnComponents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceArnAttribute", reflect.TypeOf((*MockTable)(nil).GetResourceArnAttribute), arnAttr, arnComponents)
}

// GetResourceNameAttribute mocks base method.
func (m *MockTable) GetResourceNameAttribute(nameAttr *string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceNameAttribute", nameAttr)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceNameAttribute indicates an expected call of GetResourceNameAttribute.
func (mr *MockTableMockRecorder) GetResourceNameAttribute(nameAttr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceNameAttribute", reflect.TypeOf((*MockTable)(nil).GetResourceNameAttribute), nameAttr)
}

// Grant mocks base method.
func (m *MockTable) Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant {
	m.ctrl.T.Helper()
	varargs := []interface{}{grantee}
	for _, a := range actions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Grant", varargs...)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// Grant indicates an expected call of Grant.
func (mr *MockTableMockRecorder) Grant(grantee interface{}, actions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{grantee}, actions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MockTable)(nil).Grant), varargs...)
}

// GrantFullAccess mocks base method.
func (m *MockTable) GrantFullAccess(grantee awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantFullAccess", grantee)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantFullAccess indicates an expected call of GrantFullAccess.
func (mr *MockTableMockRecorder) GrantFullAccess(grantee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantFullAccess", reflect.TypeOf((*MockTable)(nil).GrantFullAccess), grantee)
}

// GrantReadData mocks base method.
func (m *MockTable) GrantReadData(grantee awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantReadData", grantee)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantReadData indicates an expected call of GrantReadData.
func (mr *MockTableMockRecorder) GrantReadData(grantee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantReadData", reflect.TypeOf((*MockTable)(nil).GrantReadData), grantee)
}

// GrantReadWriteData mocks base method.
func (m *MockTable) GrantReadWriteData(grantee awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantReadWriteData", grantee)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantReadWriteData indicates an expected call of GrantReadWriteData.
func (mr *MockTableMockRecorder) GrantReadWriteData(grantee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantReadWriteData", reflect.TypeOf((*MockTable)(nil).GrantReadWriteData), grantee)
}

// GrantStream mocks base method.
func (m *MockTable) GrantStream(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant {
	m.ctrl.T.Helper()
	varargs := []interface{}{grantee}
	for _, a := range actions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantStream", varargs...)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantStream indicates an expected call of GrantStream.
func (mr *MockTableMockRecorder) GrantStream(grantee interface{}, actions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{grantee}, actions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantStream", reflect.TypeOf((*MockTable)(nil).GrantStream), varargs...)
}

// GrantStreamRead mocks base method.
func (m *MockTable) GrantStreamRead(grantee awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantStreamRead", grantee)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantStreamRead indicates an expected call of GrantStreamRead.
func (mr *MockTableMockRecorder) GrantStreamRead(grantee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantStreamRead", reflect.TypeOf((*MockTable)(nil).GrantStreamRead), grantee)
}

// GrantTableListStreams mocks base method.
func (m *MockTable) GrantTableListStreams(grantee awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantTableListStreams", grantee)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantTableListStreams indicates an expected call of GrantTableListStreams.
func (mr *MockTableMockRecorder) GrantTableListStreams(grantee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantTableListStreams", reflect.TypeOf((*MockTable)(nil).GrantTableListStreams), grantee)
}

// GrantWriteData mocks base method.
func (m *MockTable) GrantWriteData(grantee awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantWriteData", grantee)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantWriteData indicates an expected call of GrantWriteData.
func (mr *MockTableMockRecorder) GrantWriteData(grantee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantWriteData", reflect.TypeOf((*MockTable)(nil).GrantWriteData), grantee)
}

// HasIndex mocks base method.
func (m *MockTable) HasIndex() *bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasIndex")
	ret0, _ := ret[0].(*bool)
	return ret0
}

// HasIndex indicates an expected call of HasIndex.
func (mr *MockTableMockRecorder) HasIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasIndex", reflect.TypeOf((*MockTable)(nil).HasIndex))
}

// Metric mocks base method.
func (m *MockTable) Metric(metricName *string, props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metric", metricName, props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// Metric indicates an expected call of Metric.
func (mr *MockTableMockRecorder) Metric(metricName, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metric", reflect.TypeOf((*MockTable)(nil).Metric), metricName, props)
}

// MetricConditionalCheckFailedRequests mocks base method.
func (m *MockTable) MetricConditionalCheckFailedRequests(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricConditionalCheckFailedRequests", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricConditionalCheckFailedRequests indicates an expected call of MetricConditionalCheckFailedRequests.
func (mr *MockTableMockRecorder) MetricConditionalCheckFailedRequests(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricConditionalCheckFailedRequests", reflect.TypeOf((*MockTable)(nil).MetricConditionalCheckFailedRequests), props)
}

// MetricConsumedReadCapacityUnits mocks base method.
func (m *MockTable) MetricConsumedReadCapacityUnits(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricConsumedReadCapacityUnits", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricConsumedReadCapacityUnits indicates an expected call of MetricConsumedReadCapacityUnits.
func (mr *MockTableMockRecorder) MetricConsumedReadCapacityUnits(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricConsumedReadCapacityUnits", reflect.TypeOf((*MockTable)(nil).MetricConsumedReadCapacityUnits), props)
}

// MetricConsumedWriteCapacityUnits mocks base method.
func (m *MockTable) MetricConsumedWriteCapacityUnits(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricConsumedWriteCapacityUnits", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricConsumedWriteCapacityUnits indicates an expected call of MetricConsumedWriteCapacityUnits.
func (mr *MockTableMockRecorder) MetricConsumedWriteCapacityUnits(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricConsumedWriteCapacityUnits", reflect.TypeOf((*MockTable)(nil).MetricConsumedWriteCapacityUnits), props)
}

// MetricSuccessfulRequestLatency mocks base method.
func (m *MockTable) MetricSuccessfulRequestLatency(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricSuccessfulRequestLatency", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricSuccessfulRequestLatency indicates an expected call of MetricSuccessfulRequestLatency.
func (mr *MockTableMockRecorder) MetricSuccessfulRequestLatency(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricSuccessfulRequestLatency", reflect.TypeOf((*MockTable)(nil).MetricSuccessfulRequestLatency), props)
}

// MetricSystemErrors mocks base method.
func (m *MockTable) MetricSystemErrors(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricSystemErrors", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricSystemErrors indicates an expected call of MetricSystemErrors.
func (mr *MockTableMockRecorder) MetricSystemErrors(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricSystemErrors", reflect.TypeOf((*MockTable)(nil).MetricSystemErrors), props)
}

// MetricSystemErrorsForOperations mocks base method.
func (m *MockTable) MetricSystemErrorsForOperations(props *awsdynamodb.SystemErrorsForOperationsMetricOptions) awscloudwatch.IMetric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricSystemErrorsForOperations", props)
	ret0, _ := ret[0].(awscloudwatch.IMetric)
	return ret0
}

// MetricSystemErrorsForOperations indicates an expected call of MetricSystemErrorsForOperations.
func (mr *MockTableMockRecorder) MetricSystemErrorsForOperations(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricSystemErrorsForOperations", reflect.TypeOf((*MockTable)(nil).MetricSystemErrorsForOperations), props)
}

// MetricThrottledRequests mocks base method.
func (m *MockTable) MetricThrottledRequests(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricThrottledRequests", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricThrottledRequests indicates an expected call of MetricThrottledRequests.
func (mr *MockTableMockRecorder) MetricThrottledRequests(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricThrottledRequests", reflect.TypeOf((*MockTable)(nil).MetricThrottledRequests), props)
}

// MetricThrottledRequestsForOperation mocks base method.
func (m *MockTable) MetricThrottledRequestsForOperation(operation *string, props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricThrottledRequestsForOperation", operation, props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricThrottledRequestsForOperation indicates an expected call of MetricThrottledRequestsForOperation.
func (mr *MockTableMockRecorder) MetricThrottledRequestsForOperation(operation, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricThrottledRequestsForOperation", reflect.TypeOf((*MockTable)(nil).MetricThrottledRequestsForOperation), operation, props)
}

// MetricThrottledRequestsForOperations mocks base method.
func (m *MockTable) MetricThrottledRequestsForOperations(props *awsdynamodb.OperationsMetricOptions) awscloudwatch.IMetric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricThrottledRequestsForOperations", props)
	ret0, _ := ret[0].(awscloudwatch.IMetric)
	return ret0
}

// MetricThrottledRequestsForOperations indicates an expected call of MetricThrottledRequestsForOperations.
func (mr *MockTableMockRecorder) MetricThrottledRequestsForOperations(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricThrottledRequestsForOperations", reflect.TypeOf((*MockTable)(nil).MetricThrottledRequestsForOperations), props)
}

// MetricUserErrors mocks base method.
func (m *MockTable) MetricUserErrors(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricUserErrors", props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// MetricUserErrors indicates an expected call of MetricUserErrors.
func (mr *MockTableMockRecorder) MetricUserErrors(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricUserErrors", reflect.TypeOf((*MockTable)(nil).MetricUserErrors), props)
}

// Node mocks base method.
func (m *MockTable) Node() constructs.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node")
	ret0, _ := ret[0].(constructs.Node)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockTableMockRecorder) Node() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockTable)(nil).Node))
}

// PhysicalName mocks base method.
func (m *MockTable) PhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// PhysicalName indicates an expected call of PhysicalName.
func (mr *MockTableMockRecorder) PhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalName", reflect.TypeOf((*MockTable)(nil).PhysicalName))
}

// RegionalArns mocks base method.
func (m *MockTable) RegionalArns() *[]*string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegionalArns")
	ret0, _ := ret[0].(*[]*string)
	return ret0
}

// RegionalArns indicates an expected call of RegionalArns.
func (mr *MockTableMockRecorder) RegionalArns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegionalArns", reflect.TypeOf((*MockTable)(nil).RegionalArns))
}

// ResourcePolicy mocks base method.
func (m *MockTable) ResourcePolicy() awsiam.PolicyDocument {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourcePolicy")
	ret0, _ := ret[0].(awsiam.PolicyDocument)
	return ret0
}

// ResourcePolicy indicates an expected call of ResourcePolicy.
func (mr *MockTableMockRecorder) ResourcePolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourcePolicy", reflect.TypeOf((*MockTable)(nil).ResourcePolicy))
}

// Schema mocks base method.
func (m *MockTable) Schema(indexName *string) *awsdynamodb.SchemaOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schema", indexName)
	ret0, _ := ret[0].(*awsdynamodb.SchemaOptions)
	return ret0
}

// Schema indicates an expected call of Schema.
func (mr *MockTableMockRecorder) Schema(indexName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schema", reflect.TypeOf((*MockTable)(nil).Schema), indexName)
}

// SetResourcePolicy mocks base method.
func (m *MockTable) SetResourcePolicy(val awsiam.PolicyDocument) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetResourcePolicy", val)
}

// SetResourcePolicy indicates an expected call of SetResourcePolicy.
func (mr *MockTableMockRecorder) SetResourcePolicy(val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResourcePolicy", reflect.TypeOf((*MockTable)(nil).SetResourcePolicy), val)
}

// Stack mocks base method.
func (m *MockTable) Stack() awscdk.Stack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stack")
	ret0, _ := ret[0].(awscdk.Stack)
	return ret0
}

// Stack indicates an expected call of Stack.
func (mr *MockTableMockRecorder) Stack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stack", reflect.TypeOf((*MockTable)(nil).Stack))
}

// TableArn mocks base method.
func (m *MockTable) TableArn() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableArn")
	ret0, _ := ret[0].(*string)
	return ret0
}

// TableArn indicates an expected call of TableArn.
func (mr *MockTableMockRecorder) TableArn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableArn", reflect.TypeOf((*MockTable)(nil).TableArn))
}

// TableName mocks base method.
func (m *MockTable) TableName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// TableName indicates an expected call of TableName.
func (mr *MockTableMockRecorder) TableName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableName", reflect.TypeOf((*MockTable)(nil).TableName))
}

// TableStreamArn mocks base method.
func (m *MockTable) TableStreamArn() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableStreamArn")
	ret0, _ := ret[0].(*string)
	return ret0
}

// TableStreamArn indicates an expected call of TableStreamArn.
func (mr *MockTableMockRecorder) TableStreamArn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableStreamArn", reflect.TypeOf((*MockTable)(nil).TableStreamArn))
}

// ToString mocks base method.
func (m *MockTable) ToString() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockTableMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockTable)(nil).ToString))
}
