// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/WebSocketApi.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	awscdk "github.com/aws/aws-cdk-go/awscdk/v2"
	awsapigatewayv2 "github.com/aws/aws-cdk-go/awscdk/v2/awsapigatewayv2"
	awscloudwatch "github.com/aws/aws-cdk-go/awscdk/v2/awscloudwatch"
	awsiam "github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	constructs "github.com/aws/constructs-go/constructs/v10"
	gomock "github.com/golang/mock/gomock"
)

// MockWebSocketApi is a mock of WebSocketApi interface.
type MockWebSocketApi struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketApiMockRecorder
}

// MockWebSocketApiMockRecorder is the mock recorder for MockWebSocketApi.
type MockWebSocketApiMockRecorder struct {
	mock *MockWebSocketApi
}

// NewMockWebSocketApi creates a new mock instance.
func NewMockWebSocketApi(ctrl *gomock.Controller) *MockWebSocketApi {
	mock := &MockWebSocketApi{ctrl: ctrl}
	mock.recorder = &MockWebSocketApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketApi) EXPECT() *MockWebSocketApiMockRecorder {
	return m.recorder
}

// AddRoute mocks base method.
func (m *MockWebSocketApi) AddRoute(routeKey *string, options *awsapigatewayv2.WebSocketRouteOptions) awsapigatewayv2.WebSocketRoute {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoute", routeKey, options)
	ret0, _ := ret[0].(awsapigatewayv2.WebSocketRoute)
	return ret0
}

// AddRoute indicates an expected call of AddRoute.
func (mr *MockWebSocketApiMockRecorder) AddRoute(routeKey, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoute", reflect.TypeOf((*MockWebSocketApi)(nil).AddRoute), routeKey, options)
}

// ApiEndpoint mocks base method.
func (m *MockWebSocketApi) ApiEndpoint() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiEndpoint")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ApiEndpoint indicates an expected call of ApiEndpoint.
func (mr *MockWebSocketApiMockRecorder) ApiEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiEndpoint", reflect.TypeOf((*MockWebSocketApi)(nil).ApiEndpoint))
}

// ApiId mocks base method.
func (m *MockWebSocketApi) ApiId() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiId")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ApiId indicates an expected call of ApiId.
func (mr *MockWebSocketApiMockRecorder) ApiId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiId", reflect.TypeOf((*MockWebSocketApi)(nil).ApiId))
}

// ApplyRemovalPolicy mocks base method.
func (m *MockWebSocketApi) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyRemovalPolicy", policy)
}

// ApplyRemovalPolicy indicates an expected call of ApplyRemovalPolicy.
func (mr *MockWebSocketApiMockRecorder) ApplyRemovalPolicy(policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRemovalPolicy", reflect.TypeOf((*MockWebSocketApi)(nil).ApplyRemovalPolicy), policy)
}

// ArnForExecuteApi mocks base method.
func (m *MockWebSocketApi) ArnForExecuteApi(method, path, stage *string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArnForExecuteApi", method, path, stage)
	ret0, _ := ret[0].(*string)
	return ret0
}

// ArnForExecuteApi indicates an expected call of ArnForExecuteApi.
func (mr *MockWebSocketApiMockRecorder) ArnForExecuteApi(method, path, stage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArnForExecuteApi", reflect.TypeOf((*MockWebSocketApi)(nil).ArnForExecuteApi), method, path, stage)
}

// Env mocks base method.
func (m *MockWebSocketApi) Env() *awscdk.ResourceEnvironment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(*awscdk.ResourceEnvironment)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockWebSocketApiMockRecorder) Env() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockWebSocketApi)(nil).Env))
}

// GeneratePhysicalName mocks base method.
func (m *MockWebSocketApi) GeneratePhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// GeneratePhysicalName indicates an expected call of GeneratePhysicalName.
func (mr *MockWebSocketApiMockRecorder) GeneratePhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePhysicalName", reflect.TypeOf((*MockWebSocketApi)(nil).GeneratePhysicalName))
}

// GetResourceArnAttribute mocks base method.
func (m *MockWebSocketApi) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceArnAttribute", arnAttr, arnComponents)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceArnAttribute indicates an expected call of GetResourceArnAttribute.
func (mr *MockWebSocketApiMockRecorder) GetResourceArnAttribute(arnAttr, arnComponents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceArnAttribute", reflect.TypeOf((*MockWebSocketApi)(nil).GetResourceArnAttribute), arnAttr, arnComponents)
}

// GetResourceNameAttribute mocks base method.
func (m *MockWebSocketApi) GetResourceNameAttribute(nameAttr *string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceNameAttribute", nameAttr)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceNameAttribute indicates an expected call of GetResourceNameAttribute.
func (mr *MockWebSocketApiMockRecorder) GetResourceNameAttribute(nameAttr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceNameAttribute", reflect.TypeOf((*MockWebSocketApi)(nil).GetResourceNameAttribute), nameAttr)
}

// GrantManageConnections mocks base method.
func (m *MockWebSocketApi) GrantManageConnections(identity awsiam.IGrantable) awsiam.Grant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantManageConnections", identity)
	ret0, _ := ret[0].(awsiam.Grant)
	return ret0
}

// GrantManageConnections indicates an expected call of GrantManageConnections.
func (mr *MockWebSocketApiMockRecorder) GrantManageConnections(identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantManageConnections", reflect.TypeOf((*MockWebSocketApi)(nil).GrantManageConnections), identity)
}

// Metric mocks base method.
func (m *MockWebSocketApi) Metric(metricName *string, props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metric", metricName, props)
	ret0, _ := ret[0].(awscloudwatch.Metric)
	return ret0
}

// Metric indicates an expected call of Metric.
func (mr *MockWebSocketApiMockRecorder) Metric(metricName, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metric", reflect.TypeOf((*MockWebSocketApi)(nil).Metric), metricName, props)
}

// Node mocks base method.
func (m *MockWebSocketApi) Node() constructs.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node")
	ret0, _ := ret[0].(constructs.Node)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockWebSocketApiMockRecorder) Node() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockWebSocketApi)(nil).Node))
}

// PhysicalName mocks base method.
func (m *MockWebSocketApi) PhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// PhysicalName indicates an expected call of PhysicalName.
func (mr *MockWebSocketApiMockRecorder) PhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalName", reflect.TypeOf((*MockWebSocketApi)(nil).PhysicalName))
}

// Stack mocks base method.
func (m *MockWebSocketApi) Stack() awscdk.Stack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stack")
	ret0, _ := ret[0].(awscdk.Stack)
	return ret0
}

// Stack indicates an expected call of Stack.
func (mr *MockWebSocketApiMockRecorder) Stack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stack", reflect.TypeOf((*MockWebSocketApi)(nil).Stack))
}

// ToString mocks base method.
func (m *MockWebSocketApi) ToString() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockWebSocketApiMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockWebSocketApi)(nil).ToString))
}

// WebSocketApiName mocks base method.
func (m *MockWebSocketApi) WebSocketApiName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebSocketApiName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// WebSocketApiName indicates an expected call of WebSocketApiName.
func (mr *MockWebSocketApiMockRecorder) WebSocketApiName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebSocketApiName", reflect.TypeOf((*MockWebSocketApi)(nil).WebSocketApiName))
}
