// Code generated by MockGen. DO NOT EDIT.
// Source: lambda/Greet.go
//
// Generated by this command:
//
//	mockgen -source=lambda/Greet.go -destination=mocks/Greet.go -package=mocks Greet
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	awscdk "github.com/aws/aws-cdk-go/awscdk/v2"
	awslambda "github.com/aws/aws-cdk-go/awscdk/v2/awslambda"
	gomock "go.uber.org/mock/gomock"
)

// MockIGreet is a mock of IGreet interface.
type MockIGreet struct {
	ctrl     *gomock.Controller
	recorder *MockIGreetMockRecorder
	isgomock struct{}
}

// MockIGreetMockRecorder is the mock recorder for MockIGreet.
type MockIGreetMockRecorder struct {
	mock *MockIGreet
}

// NewMockIGreet creates a new mock instance.
func NewMockIGreet(ctrl *gomock.Controller) *MockIGreet {
	mock := &MockIGreet{ctrl: ctrl}
	mock.recorder = &MockIGreetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGreet) EXPECT() *MockIGreetMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIGreet) Create(stack awscdk.Stack) awslambda.Function {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", stack)
	ret0, _ := ret[0].(awslambda.Function)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIGreetMockRecorder) Create(stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIGreet)(nil).Create), stack)
}
