// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/Resource.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	awscdk "github.com/aws/aws-cdk-go/awscdk/v2"
	awsapigateway "github.com/aws/aws-cdk-go/awscdk/v2/awsapigateway"
	constructs "github.com/aws/constructs-go/constructs/v10"
	gomock "github.com/golang/mock/gomock"
)

// MockResource is a mock of Resource interface.
type MockResource struct {
	ctrl     *gomock.Controller
	recorder *MockResourceMockRecorder
}

// MockResourceMockRecorder is the mock recorder for MockResource.
type MockResourceMockRecorder struct {
	mock *MockResource
}

// NewMockResource creates a new mock instance.
func NewMockResource(ctrl *gomock.Controller) *MockResource {
	mock := &MockResource{ctrl: ctrl}
	mock.recorder = &MockResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResource) EXPECT() *MockResourceMockRecorder {
	return m.recorder
}

// AddCorsPreflight mocks base method.
func (m *MockResource) AddCorsPreflight(options *awsapigateway.CorsOptions) awsapigateway.Method {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCorsPreflight", options)
	ret0, _ := ret[0].(awsapigateway.Method)
	return ret0
}

// AddCorsPreflight indicates an expected call of AddCorsPreflight.
func (mr *MockResourceMockRecorder) AddCorsPreflight(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCorsPreflight", reflect.TypeOf((*MockResource)(nil).AddCorsPreflight), options)
}

// AddMethod mocks base method.
func (m *MockResource) AddMethod(httpMethod *string, target awsapigateway.Integration, options *awsapigateway.MethodOptions) awsapigateway.Method {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMethod", httpMethod, target, options)
	ret0, _ := ret[0].(awsapigateway.Method)
	return ret0
}

// AddMethod indicates an expected call of AddMethod.
func (mr *MockResourceMockRecorder) AddMethod(httpMethod, target, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMethod", reflect.TypeOf((*MockResource)(nil).AddMethod), httpMethod, target, options)
}

// AddProxy mocks base method.
func (m *MockResource) AddProxy(options *awsapigateway.ProxyResourceOptions) awsapigateway.ProxyResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProxy", options)
	ret0, _ := ret[0].(awsapigateway.ProxyResource)
	return ret0
}

// AddProxy indicates an expected call of AddProxy.
func (mr *MockResourceMockRecorder) AddProxy(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProxy", reflect.TypeOf((*MockResource)(nil).AddProxy), options)
}

// AddResource mocks base method.
func (m *MockResource) AddResource(pathPart *string, options *awsapigateway.ResourceOptions) awsapigateway.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResource", pathPart, options)
	ret0, _ := ret[0].(awsapigateway.Resource)
	return ret0
}

// AddResource indicates an expected call of AddResource.
func (mr *MockResourceMockRecorder) AddResource(pathPart, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResource", reflect.TypeOf((*MockResource)(nil).AddResource), pathPart, options)
}

// Api mocks base method.
func (m *MockResource) Api() awsapigateway.IRestApi {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Api")
	ret0, _ := ret[0].(awsapigateway.IRestApi)
	return ret0
}

// Api indicates an expected call of Api.
func (mr *MockResourceMockRecorder) Api() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Api", reflect.TypeOf((*MockResource)(nil).Api))
}

// ApplyRemovalPolicy mocks base method.
func (m *MockResource) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyRemovalPolicy", policy)
}

// ApplyRemovalPolicy indicates an expected call of ApplyRemovalPolicy.
func (mr *MockResourceMockRecorder) ApplyRemovalPolicy(policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRemovalPolicy", reflect.TypeOf((*MockResource)(nil).ApplyRemovalPolicy), policy)
}

// DefaultCorsPreflightOptions mocks base method.
func (m *MockResource) DefaultCorsPreflightOptions() *awsapigateway.CorsOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultCorsPreflightOptions")
	ret0, _ := ret[0].(*awsapigateway.CorsOptions)
	return ret0
}

// DefaultCorsPreflightOptions indicates an expected call of DefaultCorsPreflightOptions.
func (mr *MockResourceMockRecorder) DefaultCorsPreflightOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultCorsPreflightOptions", reflect.TypeOf((*MockResource)(nil).DefaultCorsPreflightOptions))
}

// DefaultIntegration mocks base method.
func (m *MockResource) DefaultIntegration() awsapigateway.Integration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultIntegration")
	ret0, _ := ret[0].(awsapigateway.Integration)
	return ret0
}

// DefaultIntegration indicates an expected call of DefaultIntegration.
func (mr *MockResourceMockRecorder) DefaultIntegration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultIntegration", reflect.TypeOf((*MockResource)(nil).DefaultIntegration))
}

// DefaultMethodOptions mocks base method.
func (m *MockResource) DefaultMethodOptions() *awsapigateway.MethodOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultMethodOptions")
	ret0, _ := ret[0].(*awsapigateway.MethodOptions)
	return ret0
}

// DefaultMethodOptions indicates an expected call of DefaultMethodOptions.
func (mr *MockResourceMockRecorder) DefaultMethodOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultMethodOptions", reflect.TypeOf((*MockResource)(nil).DefaultMethodOptions))
}

// Env mocks base method.
func (m *MockResource) Env() *awscdk.ResourceEnvironment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(*awscdk.ResourceEnvironment)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockResourceMockRecorder) Env() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockResource)(nil).Env))
}

// GeneratePhysicalName mocks base method.
func (m *MockResource) GeneratePhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// GeneratePhysicalName indicates an expected call of GeneratePhysicalName.
func (mr *MockResourceMockRecorder) GeneratePhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePhysicalName", reflect.TypeOf((*MockResource)(nil).GeneratePhysicalName))
}

// GetResource mocks base method.
func (m *MockResource) GetResource(pathPart *string) awsapigateway.IResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResource", pathPart)
	ret0, _ := ret[0].(awsapigateway.IResource)
	return ret0
}

// GetResource indicates an expected call of GetResource.
func (mr *MockResourceMockRecorder) GetResource(pathPart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockResource)(nil).GetResource), pathPart)
}

// GetResourceArnAttribute mocks base method.
func (m *MockResource) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceArnAttribute", arnAttr, arnComponents)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceArnAttribute indicates an expected call of GetResourceArnAttribute.
func (mr *MockResourceMockRecorder) GetResourceArnAttribute(arnAttr, arnComponents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceArnAttribute", reflect.TypeOf((*MockResource)(nil).GetResourceArnAttribute), arnAttr, arnComponents)
}

// GetResourceNameAttribute mocks base method.
func (m *MockResource) GetResourceNameAttribute(nameAttr *string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceNameAttribute", nameAttr)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetResourceNameAttribute indicates an expected call of GetResourceNameAttribute.
func (mr *MockResourceMockRecorder) GetResourceNameAttribute(nameAttr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceNameAttribute", reflect.TypeOf((*MockResource)(nil).GetResourceNameAttribute), nameAttr)
}

// Node mocks base method.
func (m *MockResource) Node() constructs.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node")
	ret0, _ := ret[0].(constructs.Node)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockResourceMockRecorder) Node() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockResource)(nil).Node))
}

// ParentResource mocks base method.
func (m *MockResource) ParentResource() awsapigateway.IResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParentResource")
	ret0, _ := ret[0].(awsapigateway.IResource)
	return ret0
}

// ParentResource indicates an expected call of ParentResource.
func (mr *MockResourceMockRecorder) ParentResource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParentResource", reflect.TypeOf((*MockResource)(nil).ParentResource))
}

// Path mocks base method.
func (m *MockResource) Path() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(*string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockResourceMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockResource)(nil).Path))
}

// PhysicalName mocks base method.
func (m *MockResource) PhysicalName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// PhysicalName indicates an expected call of PhysicalName.
func (mr *MockResourceMockRecorder) PhysicalName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalName", reflect.TypeOf((*MockResource)(nil).PhysicalName))
}

// ResourceForPath mocks base method.
func (m *MockResource) ResourceForPath(path *string) awsapigateway.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceForPath", path)
	ret0, _ := ret[0].(awsapigateway.Resource)
	return ret0
}

// ResourceForPath indicates an expected call of ResourceForPath.
func (mr *MockResourceMockRecorder) ResourceForPath(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceForPath", reflect.TypeOf((*MockResource)(nil).ResourceForPath), path)
}

// ResourceId mocks base method.
func (m *MockResource) ResourceId() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceId")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ResourceId indicates an expected call of ResourceId.
func (mr *MockResourceMockRecorder) ResourceId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceId", reflect.TypeOf((*MockResource)(nil).ResourceId))
}

// Stack mocks base method.
func (m *MockResource) Stack() awscdk.Stack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stack")
	ret0, _ := ret[0].(awscdk.Stack)
	return ret0
}

// Stack indicates an expected call of Stack.
func (mr *MockResourceMockRecorder) Stack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stack", reflect.TypeOf((*MockResource)(nil).Stack))
}

// ToString mocks base method.
func (m *MockResource) ToString() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(*string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockResourceMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockResource)(nil).ToString))
}
