# This workflow triggers when code is added to the staging branch.
# It runs tests for all components on a clean ubuntu image.
# If tests pass, the code is deployed to the production environment.

name: Test and Deploy

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  test-client:
    runs-on: ubuntu-latest
    container: node:22-bullseye

    steps:
    - uses: actions/checkout@v4
    - run: ./commands.sh build client
    - run: ./commands.sh test client

  test-server:
    runs-on: ubuntu-latest
    # Note that AWS CDK uses a JSII layer that requires Node.js
    container: node:22-bullseye

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.x'
    - run: ./commands.sh build server
    - run: ./commands.sh test server

  deploy:
    runs-on: ubuntu-latest
    container: node:22-bullseye
    needs: [ test-client, test-server ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.x'
    - run: ./commands.sh build
    - run: ./commands.sh deploy
